# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import server_pb2 as server__pb2


class ServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.voidFunction = channel.unary_unary(
        '/Server/voidFunction',
        request_serializer=server__pb2.void.SerializeToString,
        response_deserializer=server__pb2.void.FromString,
        )
    self.boolFunction = channel.unary_unary(
        '/Server/boolFunction',
        request_serializer=server__pb2.Bool.SerializeToString,
        response_deserializer=server__pb2.Bool.FromString,
        )
    self.intArg = channel.unary_unary(
        '/Server/intArg',
        request_serializer=server__pb2.Integer.SerializeToString,
        response_deserializer=server__pb2.Integer.FromString,
        )
    self.longArg = channel.unary_unary(
        '/Server/longArg',
        request_serializer=server__pb2.Long.SerializeToString,
        response_deserializer=server__pb2.Long.FromString,
        )
    self.stringArg = channel.unary_unary(
        '/Server/stringArg',
        request_serializer=server__pb2.String.SerializeToString,
        response_deserializer=server__pb2.String.FromString,
        )
    self.objectArg = channel.unary_unary(
        '/Server/objectArg',
        request_serializer=server__pb2.Object.SerializeToString,
        response_deserializer=server__pb2.Object.FromString,
        )
    self.stringListArg = channel.unary_unary(
        '/Server/stringListArg',
        request_serializer=server__pb2.StringArray.SerializeToString,
        response_deserializer=server__pb2.StringArray.FromString,
        )
    self.intArray = channel.unary_unary(
        '/Server/intArray',
        request_serializer=server__pb2.IntArray.SerializeToString,
        response_deserializer=server__pb2.IntArray.FromString,
        )
    self.floatArray = channel.unary_unary(
        '/Server/floatArray',
        request_serializer=server__pb2.FloatArray.SerializeToString,
        response_deserializer=server__pb2.FloatArray.FromString,
        )
    self.euclideanDistance = channel.unary_unary(
        '/Server/euclideanDistance',
        request_serializer=server__pb2.EuclidianVectors.SerializeToString,
        response_deserializer=server__pb2.Float.FromString,
        )


class ServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def voidFunction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def boolFunction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def intArg(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def longArg(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def stringArg(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def objectArg(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def stringListArg(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def intArray(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def floatArray(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def euclideanDistance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'voidFunction': grpc.unary_unary_rpc_method_handler(
          servicer.voidFunction,
          request_deserializer=server__pb2.void.FromString,
          response_serializer=server__pb2.void.SerializeToString,
      ),
      'boolFunction': grpc.unary_unary_rpc_method_handler(
          servicer.boolFunction,
          request_deserializer=server__pb2.Bool.FromString,
          response_serializer=server__pb2.Bool.SerializeToString,
      ),
      'intArg': grpc.unary_unary_rpc_method_handler(
          servicer.intArg,
          request_deserializer=server__pb2.Integer.FromString,
          response_serializer=server__pb2.Integer.SerializeToString,
      ),
      'longArg': grpc.unary_unary_rpc_method_handler(
          servicer.longArg,
          request_deserializer=server__pb2.Long.FromString,
          response_serializer=server__pb2.Long.SerializeToString,
      ),
      'stringArg': grpc.unary_unary_rpc_method_handler(
          servicer.stringArg,
          request_deserializer=server__pb2.String.FromString,
          response_serializer=server__pb2.String.SerializeToString,
      ),
      'objectArg': grpc.unary_unary_rpc_method_handler(
          servicer.objectArg,
          request_deserializer=server__pb2.Object.FromString,
          response_serializer=server__pb2.Object.SerializeToString,
      ),
      'stringListArg': grpc.unary_unary_rpc_method_handler(
          servicer.stringListArg,
          request_deserializer=server__pb2.StringArray.FromString,
          response_serializer=server__pb2.StringArray.SerializeToString,
      ),
      'intArray': grpc.unary_unary_rpc_method_handler(
          servicer.intArray,
          request_deserializer=server__pb2.IntArray.FromString,
          response_serializer=server__pb2.IntArray.SerializeToString,
      ),
      'floatArray': grpc.unary_unary_rpc_method_handler(
          servicer.floatArray,
          request_deserializer=server__pb2.FloatArray.FromString,
          response_serializer=server__pb2.FloatArray.SerializeToString,
      ),
      'euclideanDistance': grpc.unary_unary_rpc_method_handler(
          servicer.euclideanDistance,
          request_deserializer=server__pb2.EuclidianVectors.FromString,
          response_serializer=server__pb2.Float.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Server', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
